# Generated by Django 5.2.15 on 2026-06-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyservice',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
