# Generated by Django 5.2.15 on 2026-07-02 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_banner_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('id', 'ID Card / Passport'), ('certificate', 'Certification / License'), ('insurance', 'Insurance Document'), ('other', 'Other')], default='id', max_length=20)),
                ('file_url', models.URLField(max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_technician_document',
                'ordering': ['-created_at'],
            },
        ),
    ]
