# Generated by Django 5.2.15 on 2026-06-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_technicianservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
