# Generated by Django 5.2.15 on 2026-08-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_address_user_date_of_birth_user_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniciandocument',
            name='file_url',
            field=models.CharField(max_length=500),
        ),
    ]
