# Generated by Django 5.2.15 on 2026-08-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companyprofile_profile_views_companyactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='attachments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='client_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='priority',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='project_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='technical_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
