# Generated by Django 5.2.15 on 2026-08-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_quoterequest_attachments_quoterequest_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='areas_of_expertise',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='latitude',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='longitude',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='subject_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='year_founded',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
