# Generated by Django 5.2.15 on 2026-08-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_companyprofile_areas_of_expertise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyservice',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companyservice',
            name='pricing_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companyservice',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
