# Generated by Django 5.2.15 on 2026-08-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_companyservice_category_companyservice_pricing_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='traffic_direct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='traffic_external',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='traffic_recommendations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='traffic_search',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyservice',
            name='acceptance_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='companyservice',
            name='quotes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyservice',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
