# Generated by Django 5.2.15 on 2026-08-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_companyprofile_auto_accept_visits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='cover_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='logo_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='website',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
