# Generated by Django 5.2.15 on 2026-07-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_techniciandocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianservice',
            name='media',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
